HOST = "localhost"
USER = "root"
PASSWORD = ""
DATABASE_INSTAGRAM = "nr_instagram"
DATABASE_SOURCE = "nr_source"
DATABASE_FACEBOOK = "nr_facebook"
PEXEL_API_KEY = "0NMkYhKereL0Ne2PfmTECpAF7SFgy9vGzlWMY2ieB1ByvDGUpKzS3mJn"